[project]
name = "jisper"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "requests",
    "json5",
    "pyyaml",
    "gitpython",
    "typer",
    "google-generativeai",
]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }
